#!/bin/sh

configout=$1

configin=$configout

rm -f ./.config

fullconfig=".config_"$configin
if [ -e ./configfiles/template_custom/$fullconfig ]; then
	cp ./configfiles/template_custom/$fullconfig ./.config
	echo "Template configuration "$fullconfig
else
	rm -f ./.config
	echo "No configuration "$fullconfig
fi

make menuconfig

fullconfig=".config_"$configout
if [ ! -z $configout ]; then
	mv ./.config ./configfiles/template_custom/$fullconfig
	echo "Rename and move .config as "$fullconfig" to template"
else
	echo "No target for .config"
fi
