#!/bin/sh

uci set system.@system[0].zonename='America/Chicago'
uci set system.@system[0].timezone='CST6CDT,M3.2.0,M11.1.0'
uci set system.@system[0].hostname='WiFiX'
uci commit system
/etc/init.d/system restart

uci add_list network.lan.dns='8.8.8.8'
uci add_list network.lan.dns='1.1.1.1'
#uci add_list network.lan.dns='2606:4700:4700::1111'
#uci add_list network.lan.dns='2001:4860:4860::8888'
uci commit network
/etc/init.d/network restart

uci set wireless.radio0.txpower='18'
uci set wireless.radio0.channel='44'
uci set wireless.radio0.htmode='VHT40'
uci set wireless.radio0.noscan='0'
rad1=$(uci -q get wireless.radio1.txpower)
if [ ! -z "$rad1" ]; then
	uci set wireless.radio1.txpower='18'
	uci set wireless.radio1.channel='6'
	uci set wireless.radio1.htmode='HT20'
	uci set wireless.radio1.noscan='0'
fi
uci commit wireless
wifi up

uci set firewall.@defaults[-1].drop_invalid='1'
uci commit firewall
/etc/init.d/firewall restart