#!/bin/sh

uci set system.@system[0].zonename='America/Chicago'
uci set system.@system[0].timezone='CST6CDT,M3.2.0,M11.1.0'
uci set system.@system[0].hostname='WiFiX'
uci commit system
/etc/init.d/system restart